version: '3'
services:
  web:
    build: gcs_app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - ./gcs_app/src:/app/src
      - ./gcs_app/public:/app/public

  backend:
    build: backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DEBUG_NO_MAVLINK=true
